"""auto-votes

Revision ID: 744e8e8cbe47
Revises: 87ac463f2330
Create Date: 2024-08-06 05:39:09.546979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744e8e8cbe47'
down_revision: Union[str, None] = '87ac463f2330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("Votes",sa.Column(
        "post_id",sa.Integer(),nullable=False
    ),
    sa.Column("user_id",sa.Integer(),nullable=False),
    sa.PrimaryKeyConstraint("post_id","user_id"),
    sa.ForeignKeyConstraint(["post_id"],["posts.id"],ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("votes")
    # ### end Alembic commands ###
